### ISSUE TITLE
倒计时 HUD 位置设置功能

### ISSUE THREAD

**Issue by iris-cat-dev** [iriscats/DRGMod.EnemyWaveTimer#2]

**Comment by iriscats** [comment]
![Uploading A66C1843187C1D3A3DE53CD6902ADC0D.png…]()

**Comment by iris-cat-dev** [comment]
![A66C1843187C1D3A3DE53CD6902ADC0D](https://github.com/user-attachments/assets/bd324988-bfa3-4d51-8a45-6cfee443a163)
